services:
    security.access.owner_voter:
        class:      UserBundle\Security\Authorization\Voter\OwnerVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.super_admin_voter:
        class:      UserBundle\Security\Authorization\Voter\SuperAdminVoter
        public:     false
        tags:
           - { name: security.voter }